### ISSUE TITLE
Label that change dynamically are not updated

### ISSUE THREAD

**Issue by bappr** [fabric8io/fluent-plugin-kubernetes_metadata_filter#156]
My case might is very simple.

=>
I start a pod with label `app=1`.
I change dynamically the label of this pod without restarting it `app=2`

In my logs, I will always see label `app=1`.

**Comment by jcantrill** [comment]
This plugin has a caching mechanism to limit the frequency that it hits the API server to retrieve metadata.  The cache is configurable.  You can also configure the plugin to 'watch' the API server so that it proactively receives changes for pods.  I suspect you are seeing a cache entry that has not rolled over or timed out.  We traded performance over exactness.

**Comment by bappr** [comment]
Hi @jcantrill  thanks for your reply.
Was not aware of these conf, that s great thanks.

However, from the documentation:
> watch - set up a watch on pods on the API server for updates to metadata (default: true)
So watch should already be set to `true` right? Should I set the `cache_ttl` to 0 then? One does not invalidate the other?

**Comment by jcantrill** [comment]
> Hi @jcantrill thanks for your reply.
> Was not aware of these conf, that s great thanks.
> 
> However, from the documentation:
> 
> > watch - set up a watch on pods on the API server for updates to metadata (default: true)
> 
> So watch should already be set to `true` right? Should I set the `cache_ttl` to 0 then? One does not invalidate the other?

I would expect if you are going to set the `cache_ttl` to zero that would invalidate the purpose of using watch since any changes are immediately of no value.  I would expect as well as you probably don't want 0 but something significantly small, like 1 sec. We have not tested but I could imagine a race condition where you retrieve meta which gets cached, may be used in a subsequent call and then need to be fetched again

**Comment by bappr** [comment]
@jcantrill, I ll test this out. Thanks a lot for your help. :-)
It s exactly what I want! 👍
