### ISSUE TITLE
Specify kubeconfig file for auth

### ISSUE THREAD

**Issue by satnam6502** [fabric8io/fluent-plugin-kubernetes_metadata_filter#2]
Rather than breaking out the individual auth bits it might be better to just specify a kubeconfig file? That's what is generated for the secrets for `token-admin` and `token-kubelet`

**Comment by satnam6502** [comment]
@jlowdermilk

**Comment by jimmidyson** [comment]
@satnam6502 @jlowdermilk I believe that when service accounts land we should be using that instead of kubeconfig? That is covered by our use of bearer tokens so no changes should be necessary. But if we need to support kubeconfig too, then it's simple to add but I only want to do so if it's actuallu required.

**Comment by satnam6502** [comment]
Yes, agreed.

**Comment by jimmidyson** [comment]
Closing as this now uses service account if available.

**Comment by satnam6502** [comment]
I wish GitHub had a thumbs up feature.
