### ISSUE TITLE
Benchmarks for kubernetes metadata

### ISSUE THREAD

**Issue by jicowan** [fabric8io/fluent-plugin-kubernetes_metadata_filter#282]
Have folks run benchmark tests with the filter to determine:
1. When to enable caching
2. What to set the TTL to
3. When to use K8S_NODE_NAME
I'm looking for guidance that says when your cluster has X nodes or when the number of API requests from node agents exceed X, make the following changes.

**Comment by jcantrill** [comment]
> Have folks run benchmark tests with the filter to determine:

There has been benchmarking in various issues logged against this repo but you will need to search back to find them.  Nothing is explicitly published here.

> 
> 1. When to enable caching

I'm not certain what the ask specifically here is.  The implications of not caching are you are hitting the API server for every log message processed.  Pod labels don't change often enough for this to be needed and can be handled by enabling watch.  I think the performance implications of NOT caching are obvious.

> 2. What to set the TTL to

I'm not certain benchmarking is needed here but an understanding of the workloads you expect for a given node.  If the expectation is you will have long lived pods then its reasonable to set this to a longer value.  If you expect to have something like build pods or cronjobs then its reasonable these pods are short lived and you can get away with shorter TTL.  The cache size and TTL are in place as ways to balance between hitting the API server and memory consumption

> 3. When to use K8S_NODE_NAME

This parameter was added as a watch optimization so you only receive updates for the node on which the filter is running.  I would encourage setting this value anytime watch is enabled to restrict update notifications for only those pods running on a given node.

**Comment by jicowan** [comment]
Thank @jcantrill. So if you use watch you should also use K8s_NODE_NAME to narrow the scope of the watch. I didn't do a good job of phrasing my question about the cache. When would you increase the size of the cache? For example, when there are greater than x pods on the node? When there is high pods churn? What constitutes high? Does cache size scale linearly as pod churn and num pods scale?

**Comment by jcantrill** [comment]
> Thank @jcantrill. So if you use watch you should also use K8s_NODE_NAME to narrow the scope of the watch.

I don't recall but this may be added for you by the platform, especially since you generally are unable to control where a pod lands

 > I didn't do a good job of phrasing my question about the cache. When would you increase the size of the cache? For example, when there are greater than x pods on the node? 
The answer is it depends on the max capacity of your nodes.  The OpenShift team does performance testing to determine the max pod density of a node.  It seems reasonable there is no reason to set the cache size greater then that number since theoretically you will never get there.  I would argue that maybe the default setting of 1000 is too high.  It has been awhile since I reviewed that OpenShift numbers but at some point they were only capable of hosting 250 containers per node based on whatever instance size was used for the test.  I believe this has changed but max size plus 30% is probably a good safety factor.

>When there is high pods churn? What constitutes high? 
I am unable to quantify "high", but as an example, any short-lived pods would consume "cache" unnecessarily.  Those pods will generate logs for a set period of time and go away never to return.  The meta will sit in the cache until its evicted by time or frequency.  Worker nodes that are designated to be "build" workers might be good candidates where you might see "high" churn.  Additionally, cronjobs are something that are relatively short lived.

> Does cache size scale linearly as pod churn and num pods scale?
I'm not certain what exactly you are asking here.  This is the cache library used by this plugin: https://github.com/SamSaffron/lru_redux
