### ISSUE TITLE
Remove de_dot functionality from plugin

### ISSUE THREAD

**Issue by jcantrill** [fabric8io/fluent-plugin-kubernetes_metadata_filter#320]
This functionality is a hold over from the original implementation that did a log of tangential things.  Remove this functionality and refer users to alternate plugins

**Comment by aauren** [comment]
@jcantrill It makes sense that de_dot functionality would not be part of this plugin by default.

In your message though you mentioned referring users to alternate plugins, do you happen to know of a replacement for this functionality? Did this already get documented somewhere?

**Comment by jcantrill** [comment]
> In your message though you mentioned referring users to alternate plugins, do you happen to know of a replacement for this functionality? Did this already get documented somewhere?

I do not know of a specific plugin though one could use record_transformer https://github.com/repeatedly/fluent-plugin-record-modifier#ruby-code-trick-for-complex-logic

**Comment by OlleLarsson** [comment]
We recently upgraded to a version of this plugin were the de_dot feature has been removed and we encountered tons of mapping conflicts in elasticsearch/opensearch due to the removal.

I'm wondering how you have solved this, or you never encounter such mapping [problems](https://github.com/fluent/fluent-bit/issues/854)(I know it links to fluent-bit) for annotations or labels in your platform?
We'll be downgrading until we know how to approach this problem of having dots in kubernetes metadata, as the plugin no longer handles it.

**Comment by OlleLarsson** [comment]
Hi, thanks for the reply.
Looks like they have added a new feature, [subobjects](https://www.elastic.co/guide/en/elasticsearch/reference/8.4/subobjects.html), in ES8 that allows for the behavior we are looking, unfortunately we are using Opensearch which do not have that feature.
We'll have to look and see how we should proceed with this.
I was just a bit surprised when we upgraded the plugin and discovered that the default behavior of replacing dots with _  had been removed ;)
Have a nice weekend!
