### ISSUE TITLE
Working with in_forward source

### ISSUE THREAD

**Issue by nyilmaz** [fabric8io/fluent-plugin-kubernetes_metadata_filter#56]
Hi there!

As far as I read this filter's code, filter mainly assumes the source of the log messages would be `in_tail`. Hence filter can parse tags thanks to the `/var/log/containers/*.log` convention (or customizable regexp) and extracts some metadata from here. And remaining ones can be fetched by k8s client and merged.

The question is if we want to use `in_forward` as source which [does not have tag parameter](http://docs.fluentd.org/v0.12/articles/in_forward#parameters), how can we filter and extract k8s metadata from this source? What would be the cleanest approach here? Would the metadata fetched by ruby kubernates client be enough, assuming we have provided `kubernates_url` parameter to the filter?

**Comment by richm** [comment]
> filter mainly assumes the source of the log messages would be in_tail

Not exactly.  It can also process k8s container logs from journald.

> The question is if we want to use in_forward as source which does not have tag parameter,

but won't those messages have a tag set by the forwarder client?

**Comment by nyilmaz** [comment]
Tags can be set by forwarder client, however I'm not sure whether the metadata extracted from `kubernates.[log-file-path]` is available to my client, for me to pass as tags. Is there another way to catch those metadata from another way?

In short, what is the distinct difference between metadata fetched by `KubernetesClient` and matched by regex from `kubernates.[log-file-path]`?

**Comment by richm** [comment]
> Tags can be set by forwarder client

In that case:

* if `use_journal false` (the default), then the tag must exactly match what would be returned by the `in_tail` plugin using a `path /var/log/containers/*.log` and `tag kubernetes.*`.  This will produce tags that match the pattern `tag_to_kubernetes_name_regexp` which by default is  `'var\.log\.containers\.(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$'`

* if `use_journal true`, then there must be fields `CONTAINER_NAME` and `CONTAINER_FULL_ID` in the input record, where `CONTAINER_NAME` must match `container_name_to_kubernetes_regexp` which by default is `'^k8s_(?<container_name>[^\.]+)\.[^_]+_(?<pod_name>[^_]+)_(?<namespace>[^_]+)_[^_]+_[a-f0-9]{8}$'`

You can use the rewrite_tag_filter plugin to create a tag to match the above.  I suppose you could change your `tag_to_kubernetes_name_regexp` to make it easier to create a specific pattern.  You could also use a record_transformer filter to create CONTAINER_NAME and CONTAINER_FULL_ID fields in the record if using `use_journal true`.

> Is there another way to catch those metadata from another way?

I'm not sure what you mean.  You will at least need a pod name and a namespace in order to use the plugin.  And it looks as though the plugin may have problems if you do not have a regexp match for docker_id and container_name.  I suppose you could just make up some values for docker_id and container_name to fit the regexp match.  The key call is here:
```ruby
        metadata = @client.get_pod(pod_name, namespace_name)
```

> In short, what is the distinct difference between metadata fetched by KubernetesClient and matched by regex from kubernates.[log-file-path]?

The primary inputs to the plugin are the kubernetes pod_name and namespace.  As you can see from the above, both the journal and the non-journal input look for these in the tag/field value.  The plugin will make a `get_pod` request using the pod_name and the KubernetesClient to get the pod uuid, pod labels and annotations, and the spec.host field of the pod.  If `include_namespace_id true`, then the plugin will make a `get_namespace` request using the namespace name and the KubernetesClient to get the namespace uuid.

**Comment by richm** [comment]
This plugin already works with in_forward / secure_forward if the above conditions are true.  Can we close this issue?
