### ISSUE TITLE
 fluent/root_agent.rb:194:handle_emits_error: emit transaction failed: error_class=NoMethodError error="undefined method `has_key?' for #<String:0x000000025b1128>" tag="kubernetes.var.log.containers.test-2-zhrpr_project1_test-8cf58c9207eef6320076e1d5fcee36234844b5674544694f7052429e62dcda77.log" 

### ISSUE THREAD

**Issue by ayElwany** [fabric8io/fluent-plugin-kubernetes_metadata_filter#62]
facing this issue , it  is not clear  if it is  Fluentd issue  or  the fluent-plugin-kubernetes_metadata_filter issue 
FLUENTD_VERSION=0.12.32 
fluent-plugin-kubernetes_metadata_filter:0.24.0

**Comment by richm** [comment]
There are a couple of places where `record.has_key?` is used e.g.
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/filter_kubernetes_metadata.rb#L266

In these cases, you would get the error if `record` was a `String` instead of a `Hash`.  In what cases can the internal representation of the record be a `String` in fluentd?  AFAIK, that isn't correct.
